export class Register {

    constructor(
        public companyNo: string,
        public companyName: string,
        public bizStartDate: string,
        public bizExpDate: string,
        public companyPhoneNo: string,
        public companyEmail: string,
        public companyAddress: string,
        public companyPostcode: string,
        public companyState: string,
        public towTruckPlateNo: string,
        public bizOwnership: string,
        public fullName: string,
        public icNo: string,
        public dob: string,
        public gender: string,
        public nationality: string,
        public email: string,
        public mobileNo: string,
        public officeNo: string,
        public homeAddress: string,
        public homePostcode: string,
        public homeState: string,
        public mailAddress: string,
        public mailPostcode: string,
        public mailState: string,
        public role: number,
        public sys_status: string,
    ) {  }
}
